import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { http } from "../lib/api";

/**
 * Printable view of a single report on the module's template.
 * Opens as a standalone page (no header, no nav) — auto-triggers print.
 * Users choose "Save as PDF" from the browser's print dialog.
 */
export default function ReportPrint() {
  const { id } = useParams();
  const [data, setData] = useState(null);

  useEffect(() => {
    (async () => {
      const { data } = await http.get(`/reports/${id}/full`);
      setData(data);
    })();
  }, [id]);

  useEffect(() => {
    if (data) {
      const t = setTimeout(() => window.print(), 700);
      return () => clearTimeout(t);
    }
  }, [data]);

  if (!data) return <div style={{padding:40, fontFamily:"sans-serif"}}>Loading…</div>;

  const { report: r, module: m } = data;

  const cell = { border: "1px solid #cbd5e1", padding: "10px 12px", verticalAlign: "top" };
  const labelCell = { ...cell, background: "#F8FAFC", width: "32%", fontWeight: 600, color: "#1E3A5F" };

  return (
    <div style={{ padding: "28px 36px", fontFamily: "Georgia, 'Times New Roman', serif", color: "#111", background: "white" }}>
      <style>{`
        @media print {
          @page { size: A4; margin: 14mm; }
          .no-print { display: none !important; }
        }
        body { background: white !important; }
      `}</style>

      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "3px double #1E3A5F", paddingBottom: 16, marginBottom: 20 }}>
        <div>
          <p style={{ margin: 0, fontSize: 11, letterSpacing: 3, color: "#6B7280", textTransform: "uppercase" }}>Maktab Rendah Sains Mara</p>
          <h1 style={{ margin: "4px 0 0", fontSize: 30, letterSpacing: -0.5 }}>
            DocAtt · <span style={{ color: "#1E3A5F" }}>MRSM Kuching</span>
          </h1>
          <p style={{ margin: "6px 0 0", fontWeight: 700, color: "#B45309", fontSize: 12, letterSpacing: 2 }}>
            MRSM KUCHING NO1 · BERDISIPLIN BERILMU BERAMAL
          </p>
        </div>
        <img src="/mrsm-logo.png" alt="MRSM" style={{ height: 90, width: 90, objectFit: "contain" }} />
      </header>

      <div style={{ marginBottom: 8 }}>
        <span style={{ display: "inline-block", padding: "4px 10px", borderRadius: 999, background: "#EEF2FF", color: "#4F46E5", fontSize: 11, fontWeight: 700, letterSpacing: 1 }}>
          {r.form} · {r.homeroom}
        </span>
      </div>
      <h2 style={{ margin: "6px 0 4px", fontSize: 24 }}>{m.title || "Module Report"}</h2>
      {m.description && <p style={{ margin: 0, color: "#4B5563", fontSize: 14 }}>{m.description}</p>}

      {m.image && (
        <div style={{ margin: "18px 0" }}>
          <img src={m.image} alt="" style={{ maxWidth: "100%", maxHeight: 240, borderRadius: 8, border: "1px solid #E5E7EB" }} />
        </div>
      )}

      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 20, fontSize: 14 }}>
        <tbody>
          <tr>
            <td style={labelCell}>Meeting Report</td>
            <td style={cell}>{r.meeting_report || "—"}</td>
          </tr>
          <tr>
            <td style={labelCell}>Date</td>
            <td style={cell}>{r.date || "—"}</td>
          </tr>
          <tr>
            <td style={labelCell}>Submitted By</td>
            <td style={cell}>{r.submitted_by_name} ({r.submitted_by_role})</td>
          </tr>
          {r.description && (
            <tr>
              <td style={labelCell}>Description</td>
              <td style={cell}>{r.description}</td>
            </tr>
          )}
          {(m.custom_fields || []).map((cf, i) => (
            <tr key={i}>
              <td style={labelCell}>{cf.label}</td>
              <td style={cell}>{(r.custom_values || {})[cf.label] || "—"}</td>
            </tr>
          ))}
          {r.hr_upload_name && (
            <tr>
              <td style={labelCell}>HR Upload</td>
              <td style={cell}>{r.hr_upload_name}</td>
            </tr>
          )}
        </tbody>
      </table>

      {r.attendance_image && (
        <div style={{ marginTop: 24 }}>
          <h3 style={{ margin: "0 0 8px", fontSize: 16, color: "#1E3A5F" }}>Attendance</h3>
          <img src={r.attendance_image} alt="attendance" style={{ maxWidth: "100%", maxHeight: 420, borderRadius: 8, border: "1px solid #E5E7EB" }} />
        </div>
      )}

      <footer style={{ marginTop: 32, paddingTop: 12, borderTop: "1px solid #E5E7EB", display: "flex", justifyContent: "space-between", fontSize: 11, color: "#6B7280" }}>
        <span>Generated by DocAtt · {new Date().toLocaleString()}</span>
        <span>Report ID: {r.id.slice(0, 8)}</span>
      </footer>

      <div className="no-print" style={{ marginTop: 24, textAlign: "center" }}>
        <button onClick={() => window.print()} style={{ padding: "10px 20px", background: "#1E3A5F", color: "white", border: 0, borderRadius: 8, cursor: "pointer", fontWeight: 600 }}>
          Print / Save as PDF
        </button>
      </div>
    </div>
  );
}
